// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResetZoom
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "fdb8534b-88ef-4dc8-925b-78cefe32f930";
        public const string guidPackageCmdSetString = "c14d9719-5a4a-4497-8974-99cb6cd24d61";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ResetCommand = 0x0100;
    }
}
