// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResetZoom
{
    internal sealed partial class Vsix
    {
        public const string Id = "0a987da3-4577-4eec-aaa9-a4c2cdd5d22b";
        public const string Name = "Reset Zoom";
        public const string Description = @"Adds a command to reset the editor zoom level to 100% with a customizable keyboard shortcut. Defaults is Ctrl+0";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Mads Kristensen";
        public const string Tags = "zoom, reset, font, size";
    }
}
